name: Commit Testing

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: clear cache(?)
      run: rm -rf ~/.gradle
    - name: Build mod jar
      run: ./gradlew deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
    - name: clear cache(?) 2
      run: rm -rf ~/.gradle
      with:
        name: binary0011
        path: build/libs/${{ github.event.repository.name }}.jar
