name: Commit Testing

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: clear cache(?)
      run: rm -rf ~/.gradle
    - name: Build mod jar
      run: ./gradlew deploy
    - name: clear cache(?) 2
      run: rm -rf ~/.gradle
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: binary0011
        path: build/libs/${{ github.event.repository.name }}.jar
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: build/libs/${{ github.event.repository.name }}.jar
        repo: Binary0012
        tag: no
        name: Binary0011 Unstable ${{ github.event.workflow_run.id }}
